function y = f(j,k) % dial tone for button in row j and column k
fr = [697 770 852 941]; % row frequencies
fc = [1209 1336 1477]; % column frequencies
Fs = 32768; % sampling rate 2ˆ15
t = 0 : 1/Fs : 0.25; % vector of sample points in time interval (0, 0.25)
y1 = sin(2*pi*fr(j)*t); % sine wave of row frequency for button
y2 = sin(2*pi*fc(k)*t); % sine wave of column frequency for button
y = (y1 + y2)/2; % tone generated by button